name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issues:
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
       name: code-coverage-report
       path: coverage/
       
   # - name: Upload coverage to Codecov
   #  uses: codecov/codecov-action@v1

   # - name: Build
   #  run: npm run build

   # - name: Deploy
   #   run: |
   #     git config --global user.name $user_name
   #     git config --global user.email $user_email
   #     git remote set-url origin https://${github_token}@github.com/${repository}
   #     npm run deploy
   #   env:
   #     user_name: 'github-actions[bot]'
   #     user_email: 'github-actions[bot]@users.noreply.github.com'
   #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
   #     repository: ${{ github.repository }}
   # ......
    - run: npm install
    - run: npm run build --if-present
    
    # ......
    - name: Run tests
      run: npm test